# Generated by Django 5.2.8 on 2025-12-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='date_added',
            new_name='date_add',
        ),
    ]
