# Generated by Django 5.2.8 on 2025-11-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_pizza_name_topping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
