# Generated by Django 5.2.8 on 2025-12-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_rename_date_added_pizza_date_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
